language: python
python:
    - "2.7"
    - "3.3"
install:
    - pip install git+https://github.com/ellisonbg/altair
    - pip install -r requirements.txt -e .
    - cp remotespark/default_config.json ~/.sparkmagic/config.json
script: nosetests
