language: python
python:
    - "2.7"
    - "3.3"
install:
    - pip install -r requirements.txt -e .
    - mkdir ~/.sparkmagic
    - cp remotespark/example_config.json ~/.sparkmagic/config.json
script: nosetests
