name: Publish Packages

on:
  release:
    types: [released]


jobs:
  build:
    env:
      PYPI_TOKEN_AUTOVIZWIDGET: ${{ secrets.PYPI_TOKEN_AUTOVIZWIDGET }}
      PYPI_TOKEN_HDIJUPYTERUTILS: ${{ secrets.PYPI_TOKEN_HDIJUPYTERUTILS }}
      PYPI_TOKEN_SPARKMAGIC: ${{ secrets.PYPI_TOKEN_SPARKMAGIC }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup PyPI
        run: |
          cat > ~/.pypirc <<- EOF
          [distutils]
          index-servers =
              pypi
              pypitest

          [autovizwidget]
          username=__token__
          password=$PYPI_TOKEN_AUTOVIZWIDGET

          [hdijupyterutils]
          username=__token__
          password=$PYPI_TOKEN_HDIJUPYTERUTILS

          [sparkmagic]
          username=__token__
          password=$PYPI_TOKEN_SPARKMAGIC

          EOF

      - name: Upgrade dependencies
        run: |
          pip install -U pip setuptools twine
      - name: Release
        run: |

          /bin/sh deploy.sh
